---
title: "Plotly"
author: "Kim Kirk"
date: "April 18, 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}
using<-function(...) {
    libs<-unlist(list(...))
    req<-unlist(lapply(libs,require,character.only=TRUE))
    need<-libs[req==FALSE]
    n<-length(need)
    if(n>0){
        libsmsg<-if(n>2) paste(paste(need[1:(n-1)],collapse=", "),",",sep="") else need[1]
        print(libsmsg)
        if(n>1){
            libsmsg<-paste(libsmsg," and ", need[n],sep="")
        }
        libsmsg<-paste("The following packages could not be found: ",libsmsg,"\n\r\n\rInstall missing packages?",collapse="")
        if(winDialog(type = c("yesno"), libsmsg)=="YES"){       
            install.packages(need)
            lapply(need,require,character.only=TRUE)
        }
    }
}

using("plotly")
```

#
```{r, echo = FALSE}


nigerianCities <- data.frame(city = c("Abuja","Benin City", "Enugu", "Ibadan","Kano", "Lagos", "Port Harcourt"),
                             population = c(776298, 1495800, 3267837, 3034200, 9383682, 9013534, 1865000), 
                             latitude = c(9.066667, 6.333333, 6.452667, 7.396389, 12, 6.455027, 4.824167), 
                             longitude = c(7.483333, 5.622222, 7.510333, 3.916667, 8.516667, 3.384082, 7.033611) 
)


myPlotlyPlot <- plot_ly(nigerianCities, x= ~city, y= ~population, color = ~city, type =  "bar")
layout(myPlotlyPlot, title = "Nigerian Cities by Population")

```


